import type { Metadata } from "next";
import "./globals.css";
import SessionProvider from "@/lib/SessionProvider";
import { auth } from "@/auth";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

import { Navbar } from "@/components/navbar/Navbar";
import { ThemeProvider } from "@/components/ThemeProvider";
export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await auth();
  return (
    <html lang="en">
      <body>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <SessionProvider session={session}>
            <div className="z-2">
              <Navbar />
            </div>
            {children}
          </SessionProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
